### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'senderemail' of undefined

### ISSUE THREAD

**Issue by aniruddhac99** [arihant-jain-09/discord-clone#2]
![image](https://user-images.githubusercontent.com/32986394/117255139-ea8df080-ae66-11eb-8b7a-a4538a05c2dc.png)

**Comment by arihant-jain-09** [comment]
When did you faced this issue?  
```js
const channelRef=firestore.collection('servers').doc(currentserverid).collection('channels').doc(id).collection('messages');
const query=channelRef.orderBy('createdAt','desc').limit(1);
const [messages]=useCollectionData(query,{idField:'id'});
```
the above code gets the latest message, I have used react-firebase-hooks to get messages and then query to limit to 1.
You may see image link included for firestore database architecture..

![2021-05-06 21_50_41-Clipboard](https://user-images.githubusercontent.com/66168181/117332266-3e272b00-aeb5-11eb-9435-844b84c95a09.png)

```js
if(messages[0].senderemail===auth.currentUser.email){
     const messageRef=channelRef.doc(messages[0].id);
     await messageRef.update({
     message:messages[0].message+'\\n'+formValue
  },{merge:true})
}
```

**Comment by arihant-jain-09** [comment]
I just cloned my repo and did not faced any error

**Comment by aniruddhac99** [comment]
> I just cloned my repo and did not faced any error

## **Just fixed the issue. :+1:** 

<p>Added an 
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining">Optional Chaining Operator </a>  in line 56 of 
<a href="https://github.com/arihant-jain-09/discord-clone/blob/master-node/src/components/ChatSearchBar/ChatSearchBar.jsx">ChatSearchBar.jsx file</a>, just after messages[0] 
</p>

### **Before:** 
![image](https://user-images.githubusercontent.com/32986394/117361309-80616400-aed7-11eb-8914-b89347c71b1d.png)

### **After:** 
![image](https://user-images.githubusercontent.com/32986394/117360893-f0231f00-aed6-11eb-9fda-eb116f39d473.png)
